- name: Clone a source code repository
  hosts: all
  gather_facts: no
  become: yes
  become_user: molecule
  tasks:
    - name: Wipe {{ pipeline_dir }}
      file:
        path: "{{ pipeline_dir }}"
        state: absent

    - name: Create checkout base dir in {{ pipeline_dir }}
      file:
        path: "{{ pipeline_dir }}"
        state: directory
        mode: 0755

    - name: Clone repository {{ pipeline_repository }}
      git:
        repo: "{{ pipeline_repository}}"
        dest: "{{ pipeline_dir }}/"
