- name: Publish collection
  hosts: all
  gather_facts: no
  become: yes
  become_user: molecule
  tasks:
    - name: Build collection in  {{ pipeline_dir }}
      command: /usr/bin/ansible-galaxy collection build --force
      args:
        chdir: "{{ pipeline_dir }}"

    - set_fact:
        galaxy_config: "{{ lookup('file', 'galaxy.yml') | from_yaml}}"

    - name: Publish collection to galaxy
      command: "/usr/bin/ansible-galaxy collection publish {{ galaxy_config.namespace }}-{{ galaxy_config.name }}-{{ galaxy_config.version }}.tar.gz  -s https://{{ pipeline_galaxy_host }}/api/galaxy/content/inbound-{{ galaxy_config.namespace }}/ --api-key {{ pipeline_galaxy_api_key }} --ignore-certs"
      args:
        chdir: "{{ pipeline_dir }}"
